// Mocks generated by Mockito 5.0.16 from annotations
// in the_resident_zombie/test/features/item/data/repository/items_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:the_resident_zombie/features/items/data/datasource/items_local_datasource.dart'
    as _i2;
import 'package:the_resident_zombie/features/items/domain/entities/item_entity.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ItemsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsLocalDataSource extends _i1.Mock
    implements _i2.ItemsLocalDataSource {
  MockItemsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ItemEntity>> getItemsType() => (super.noSuchMethod(
          Invocation.method(#getItemsType, []),
          returnValue: Future<List<_i4.ItemEntity>>.value(<_i4.ItemEntity>[]))
      as _i3.Future<List<_i4.ItemEntity>>);
  @override
  String toString() => super.toString();
}
