// Mocks generated by Mockito 5.0.16 from annotations
// in the_resident_zombie/test/features/item/domain/usecases/get_items_type_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:the_resident_zombie/core/error/failures.dart' as _i5;
import 'package:the_resident_zombie/features/items/domain/entities/item_entity.dart'
    as _i6;
import 'package:the_resident_zombie/features/items/domain/repository/items_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ItemsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsRepository extends _i1.Mock implements _i3.ItemsRepository {
  MockItemsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>> getItemsType() =>
      (super.noSuchMethod(Invocation.method(#getItemsType, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.ItemEntity>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>);
  @override
  String toString() => super.toString();
}
