// Mocks generated by Mockito 5.0.16 from annotations
// in the_resident_zombie/test/features/item/data/datasource/item_local_datasource_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:the_resident_zombie/core/platform/file_getter.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [FileGetter].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileGetter extends _i1.Mock implements _i2.FileGetter {
  MockFileGetter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getFile(String? name) =>
      (super.noSuchMethod(Invocation.method(#getFile, [name]),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  String toString() => super.toString();
}
